services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Expose port 3000 to the host
    depends_on:
      - backend  # Ensure the backend service is available before starting frontend

  # Backend service (MySQL in this case)
  backend:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: T#9758@qlph
      MYSQL_DATABASE: myapp_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Expose MySQL port
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge






